site_name: Pegasus Docs
site_url: http://www.pegasus-frontend.org/docs
site_description: Documentation and customization guides for the Pegasus frontend.
site_author: M치ty치s Mustoha
copyright: Copyright &copy; 2018-2021 M치ty치s Mustoha

nav:
  - Home: index.md
  - User Guide:
    - Setup:
      - Getting started: user-guide/getting-started.md
      - Default controls: user-guide/controls.md
      - Portable mode: user-guide/portable.md
      - Config directories: user-guide/config-dirs.md
    - Platform notes:
      - Windows: user-guide/platform-windows.md
      - Android: user-guide/platform-android.md
      - Android example: user-guide/platform-android-example.md
      - Linux: user-guide/platform-linux.md
      - Raspberry Pi: user-guide/platform-raspberry.md
    - Adding games:
      - How to add games: user-guide/adding-games.md
      - Metadata files: user-guide/meta-files.md
      - Asset files: user-guide/meta-assets.md
      - Other sources: user-guide/meta-sources.md
    - Installing themes: user-guide/installing-themes.md
    - Scripting: user-guide/scripting.md
    - Breaking changes: user-guide/breaking-changes.md
  - Theme Dev:
    - Overview: themes/overview.md
    - Special features: themes/extra.md
    - QML tutorials: themes/qml-tutorials.md
    - QML modules: themes/qml-modules.md
    - "Step-by-step: Simple theme":
      - Introduction: themes/example-simple-intro.md
      - Part 1: themes/example-simple-ch1.md
      - Part 2: themes/example-simple-ch2.md
      - Part 3: themes/example-simple-ch3.md
    - "Step-by-step: Flixnet theme":
      - Introduction: themes/example-flixnet-intro.md
      - Part 1: themes/example-flixnet-ch1.md
      - Part 2: themes/example-flixnet-ch2.md
      - Part 3: themes/example-flixnet-ch3.md
      - Part 4: themes/example-flixnet-ch4.md
      - Part 5: themes/example-flixnet-ch5.md
    - API reference: themes/api.md
  - Core Dev:
    - Translations: dev/translate.md
    - Metadata syntax: dev/meta-syntax.md
    - Building: dev/build.md
    - Installing Qt: dev/install-qt.md
    - Cross compiling Qt: dev/cross-compile-qt.md
    - Deployment: dev/deploy.md

theme:
  name: cinder
  custom_dir: cinder_custom
extra_css:
  - css/extra.css
  - css/codehl.css
  - //fonts.googleapis.com/icon?family=Material+Icons

markdown_extensions:
  - toc
  - sane_lists
  - admonition
  - def_list
  - codehilite:
      guess_lang: false
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.details
  - markdown.extensions.md_in_html
